### PR TITLE
Updating defaults.yaml solr start command for all new images

### PR DESCRIPTION
**Pull request by sk33lz**
This PR is in prep for updating all of our existing images to using the newer ansible provisioner, which no longer includes the solr start script that our older puppet provisioned images used. Newly generated images with ansible use a standard service start command instead.

**Note:** This PR should be merged during our upcoming image security updates. After this PR is merged old images provisioned with puppet will not start properly, as the solr start script is not called in the defaults.yaml.

### CODE REVIEW

**Comment by dzink** [comment]
@jason I don't understand why this would affect older builds.

Does that list of services get run on containers that are woken up?

**Comment by sk33lz** [comment]
The reason it would affect older builds is that the command we use for newer images built with ansible will fail on trying to run a script that doesn't exist to start solr.

**Comment by sk33lz** [comment]
Note: It won't affect builds already created in a container, but it will affect the next build the user tries to run on that PR.

**Comment by sk33lz** [comment]
Ultimately we just need to make sure we triage this with when we deploy the new images so that we don't crash new builds because of the new way solr starts vs. the way it did on the old puppet provisioned images.

**Comment by dzink** [comment]
@sk33lz We discussed in Hipchat. +1 over here.

**Comment by sk33lz** [comment]
I need to update the image names for the new image naming convention I have in place for the newer images. We can also leave in the old commands for some of the older images until we completely pull them, as I changed up the naming convention on the tags to be a bit more logical.

Taking this back to update the code with new image names and commands where needed.

**Comment by sk33lz** [comment]
I've switched back the images we are going to keep around during the transition to use the older solr start script command and added the newer image tags that I came up with that have the newer naming convention. Testing a bunch of the images locally before this is able to be ready for primetime.

**Comment by sk33lz** [comment]
We aren't keeping the old images around with the transition to the new naming convention anymore. It's just too many images to generate. We can look at all the builds that are alseep and see what images they are using and just make sure to contact those organizations before the transition.

**Comment by sk33lz** [comment]
I've got all the solr commands updated to use the new syntax. I've removed the PHP 5.5 images, as we no longer should be supporting this PHP version. I've also set the new default image to `proboci/ubuntu-14.04-lamp:php-5.6`. This version should cause the least amount of disruption for most users, as most just use the old default image.

**Comment by sk33lz** [comment]
I added in the changes from #120 as they were closely related and it will help speed up our deployment of these changes.

**Pull request merged**
