### PR TITLE
Feature/lol/drupal 8 settings

### PR DESCRIPTION
**Pull request by lliss**
### Solution
 - Added `drupalVersion` support to .probo.yaml file.
 - Default `drupalVersion` to 7.
 - If building a D8 site, clear caches immediately after the DB import.

### To test
 - Create a new branch for a Probo enabled project (needs to be one with a database that will import).
 - Add `drupalVersion: 8` to the .probo.yaml file (ok even if you don't have a D8 site for now).
 - Create a PR.
 - Check to see that the caches were cleared twice, once after the DB import and once at the end.

### CODE REVIEW

**Comment by lliss** [comment]
> In D8 we can't actually run cache-clear, we need to run cache-rebuild. We definitely need to try this on a D8 sites. I don't think we ned to run it twice but we need to run it before updating the database. Is there still a features revert in D8? Probably not.

I added a commit to ensure we run `cache-rebuild` when on D8 sites instead of `cache-clear`. Since features exists on D8 some people must be using it for some reason, I think it is worth letting the setting to revert features continue to work even on D8.

**Comment by drnikki** [comment]
Hie!  I've got a D8 site on probo and everything is working great except my drupal task is failing with an error on `drush cc all` because it's deprecated.  I'd love to see this merged in. Everything else is *magically wonderful*

**Comment by lliss** [comment]
I'd like to bump the priority on this since we have a user who needs it (see above). @zanchin Would you mind giving this a once over.

**Comment by tizzo** [comment]
I don't think @zanchin has enough Drupal context - I'll bump this up my
priority list.

OH HAI @drnikki!!!!!! Thanks for the feedback! :D

**Comment by FatherShawn** [comment]
> Since features exists on D8 some people must be using it for some reason, I think it is worth letting the setting to revert features continue to work even on D8.

I would expect much more common will be `drush config-import` to import configuration exported to code and commited.

**Comment by drnikki** [comment]
I can't comment on how other people would use features, but after 4 months of D8 usage, I've never had do do anything other than `drush config-import` and `drush config-export`

**Comment by drnikki** [comment]
Me right now.
a3iwyhkec0p32

**Pull request merged**
