### PR TITLE
Adding StaticApp plugin.

### PR DESCRIPTION
**Pull request by sk33lz**
I started working on a StaticApp plugin based on all the demos I am doing with static site generators.

So far it has the following options:

- buildDirectory - Sets the directory where the static build files are located.

Coming soon:

- buildCommands - A set of commands to run to build the static site from the /src dir.

### CODE REVIEW

**Comment by ElusiveMind** [comment]
@sk33lz - I am going to make a dev and stage branch for this so we're not merging direct to Master prior to dev and stage testing.

**Comment by ElusiveMind** [comment]
Also do we have staged documentation for this?

**Comment by sk33lz** [comment]
This is something I put together because of how often I was setting up static sites for demos during my sessions. I still need to put together some documentation for it before we can release it into the wild.

**Comment by ElusiveMind** [comment]
I can assist with that if you like. I can see how it works. happy to help out if desired.

**Pull request closed without merging**
